version: "3"

services:
  all:
    image: eturkes/s305n-clines-rnaseq:v4
    volumes:
      - ".:/home/rstudio/s305n-clines-rnaseq:rw"
    command: Rscript -e "source('/home/rstudio/s305n-clines-rnaseq/R/run_all.R')"

  rstudio:
    image: eturkes/s305n-clines-rnaseq:v4
    volumes:
      - ".:/home/rstudio/s305n-clines-rnaseq:rw"
    ports:
      - "127.0.0.1:${PORT}:8787"
    environment:
      -  DISABLE_AUTH=true
      -  RSTUDIO_SESSION_TIMEOUT=0
